// ═══════════════════════════════════════════════════════════════════════════════
// AlphaFlow Suite — frontend/src/utils/bffClient.ts
// BFF API Client — EOA-authenticated requests to Backend-for-Frontend
//
// SECURITY:
// - Frontend holds NO secrets
// - HMAC signature comes from URL params (generated by TEE agent → BFF)
// - EOA wallet signature proves user identity
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Configuration ────────────────────────────────────────────────────────────

const BFF_BASE_URL = import.meta.env.VITE_BFF_HTTP_URL ?? "https://bff.alphaflow.suite";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ProposalData {
  id: string;
  asset: string;
  assetSymbol: string;
  action: "BUY" | "SELL";
  recommendedAmount: string; // BigInt as string
  nonce: number;
  deadline: number;
  reasoningHash: string;
  signature: string;
  signerAddress: string;
  generatedAt: number;
}

export interface EIP712Payload {
  domain: Record<string, unknown>;
  types: Record<string, Array<{ name: string; type: string }>>;
  primaryType: string;
  message: Record<string, unknown>;
}

export interface ConsumeResult {
  success: boolean;
  txHash?: string;
}

// ─── Error Class ──────────────────────────────────────────────────────────────

export class BffApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string
  ) {
    super(message);
    this.name = "BffApiError";
  }
}

export function formatBffError(err: BffApiError): string {
  switch (err.code) {
    case "PROPOSAL_EXPIRED":
      return "Proposal has expired. Wait for a new one from TEE agent.";
    case "PROPOSAL_CONSUMED":
      return "This proposal was already executed.";
    case "INVALID_SIGNATURE":
      return "HMAC signature is invalid. The link may be corrupted.";
    case "NOT_FOUND":
      return "Proposal not found.";
    default:
      return `BFF Error [${err.status}]: ${err.message}`;
  }
}

// ─── API Methods ──────────────────────────────────────────────────────────────

/**
 * Fetch proposal data from BFF.
 * Validates HMAC signature server-side.
 */
export async function fetchProposal(
  proposalId: string,
  hmacSignature: string
): Promise<ProposalData> {
  const url = `${BFF_BASE_URL}/api/proposals/${encodeURIComponent(proposalId)}`;

  const res = await fetch(url, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      "X-HMAC-Signature": hmacSignature,
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ code: "UNKNOWN", message: res.statusText }));
    throw new BffApiError(res.status, body.code ?? "UNKNOWN", body.message ?? res.statusText);
  }

  return res.json();
}

/**
 * Submit signed proposal for on-chain execution.
 * BFF verifies EOA signature then submits the transaction.
 */
export async function consumeProposal(
  proposalId: string,
  signature: string,
  signerAddress: string
): Promise<ConsumeResult> {
  const url = `${BFF_BASE_URL}/api/proposals/${encodeURIComponent(proposalId)}/execute`;

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ signature, signerAddress }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ code: "UNKNOWN", message: res.statusText }));
    throw new BffApiError(res.status, body.code ?? "UNKNOWN", body.message ?? res.statusText);
  }

  return res.json();
}
